#!/usr/bin/env bash
# Builds a double-clickable macOS app around the scripts that already exist.
#
#     bash _tools/mac-app.sh              build into the repository root
#     bash _tools/mac-app.sh ~/Applications
#
# The bundle holds no logic of its own. It runs vm-run-macos.sh, waits for the
# guest, runs engine-run.sh and opens the viewer, reporting each step as a
# notification because a Finder-launched app has nowhere to print. Everything
# it needs must already be in place: brew install qemu, and the artifacts in
# _vm from docker/eos.sh export.
set -e

BASE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="${1:-$BASE}"
APP="$DEST/Engine OS.app"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"

cat > "$APP/Contents/Info.plist" <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleName</key>            <string>Engine OS</string>
    <key>CFBundleDisplayName</key>     <string>Engine OS (QEMU)</string>
    <key>CFBundleIdentifier</key>      <string>local.engine-os-emu</string>
    <key>CFBundleVersion</key>         <string>1.0</string>
    <key>CFBundleShortVersionString</key> <string>1.0</string>
    <key>CFBundlePackageType</key>     <string>APPL</string>
    <key>CFBundleExecutable</key>      <string>engine-os</string>
    <key>LSMinimumSystemVersion</key>  <string>12.0</string>
    <key>NSHighResolutionCapable</key> <true/>
</dict>
</plist>
PLIST

cat > "$APP/Contents/MacOS/engine-os" <<LAUNCHER
#!/bin/bash
# Generated by _tools/mac-app.sh. Edit that, not this.
REPO="$BASE"
LAUNCHER

cat >> "$APP/Contents/MacOS/engine-os" <<'LAUNCHER'
# Finder gives an app a minimal PATH, without the Homebrew prefixes where qemu
# and its tools live.
export PATH="/opt/homebrew/bin:/usr/local/bin:$PATH"

say() { osascript -e "display notification \"$1\" with title \"Engine OS\"" > /dev/null 2>&1; }
fail() {
    osascript -e "display dialog \"$1\" with title \"Engine OS\" buttons {\"OK\"} default button 1 with icon stop" > /dev/null 2>&1
    exit 1
}

cd "$REPO" 2>/dev/null || fail "The repository is no longer at:\n$REPO\n\nRebuild the app with _tools/mac-app.sh."
command -v qemu-system-arm > /dev/null || fail "qemu-system-arm was not found.\n\nInstall it with:  brew install qemu"
[ -f "$REPO/_vm/rootfs-vm.img" ] || fail "No VM images in _vm.\n\nBuild them first, then:  bash docker/eos.sh export"

# The password is in the URL on purpose: Screen Sharing refuses a VNC server
# that offers no authentication, and prompts for credentials nothing can
# satisfy. See the note in vm-run-macos.sh.
VIEW="vnc://:${VNC_PASSWORD:-engineos}@localhost:5903"

vssh() {
    ssh -p 2222 -i /tmp/id_vm_macos -o StrictHostKeyChecking=no \
        -o UserKnownHostsFile=/dev/null -o ConnectTimeout=8 -o LogLevel=ERROR \
        root@127.0.0.1 "$@" 2>/dev/null
}
cp -f "$REPO/_vm/id_vm" /tmp/id_vm_macos 2>/dev/null; chmod 600 /tmp/id_vm_macos

# Three states to land in, not two: the VM can be up with Engine already
# drawing, up with Engine gone (a crash, or a stop that left the VM alone), or
# down. Only the first is finished.
if pgrep -f 'qemu-system-arm -global' > /dev/null; then
    open "$VIEW"
    if vssh 'pidof Engine' | grep -q .; then
        say "Already running. Opening the viewer."
        exit 0
    fi
    say "The VM is up but Engine is not. Restarting it."
    MESA24=1 bash "$REPO/_tools/engine-run.sh" >> /tmp/engine-os-app.log 2>&1 \
        || fail "Engine did not start. See /tmp/engine-os-app.log"
    say "Engine is drawing again."
    exit 0
fi

say "Starting the VM."
bash "$REPO/_tools/vm-run-macos.sh" > /tmp/engine-os-app.log 2>&1 \
    || fail "The VM did not start. See /tmp/engine-os-app.log"

say "Booting Engine OS. This takes about half a minute."
i=0
until vssh 'echo ready' | grep -q ready; do
    i=$((i + 1))
    [ $i -gt 60 ] && fail "The guest never answered over SSH.\n\nSee $REPO/_vm/boot.log"
    sleep 5
done

# Opened before Engine, so the first frame is watched as it arrives rather than
# after a minute of nothing.
open "$VIEW"

say "Starting Engine DJ. The first frame takes a minute or so."
MESA24=1 bash "$REPO/_tools/engine-run.sh" >> /tmp/engine-os-app.log 2>&1 \
    || fail "Engine did not start. See /tmp/engine-os-app.log"

say "Engine is drawing. Stop it with: vm-run-macos.sh --stop"
LAUNCHER

chmod +x "$APP/Contents/MacOS/engine-os"
touch "$APP"
echo "built: $APP"
echo "The bundle carries no icon: the only artwork to hand is the vendor's."
